Update dependencies
http had to be updated to address a bug printing an empty response
  FrozenError: can't modify frozen String

jmespath and addressable had warnings from dependabot